////////////////////////////////////////////////////////////
// TucanEmailMessage (idl definition)
//
// Copyright (C) 2000, Difinium
////////////////////////////////////////////////////////////
// Filename:        TucanEmailMessage.idl
// Description:     idl definition of TucanEmailMessage
// Created at:      Thu Jul 27 15:57:28 PDT 2000
////////////////////////////////////////////////////////////

interface TucanEmailMessage : TucanMessage {};

interface TucanEmailMessageFactory : TucanMessageFactory {};
